### ISSUE TITLE
기능 추가 가능하신지 문의 드립니다.

### ISSUE THREAD

**Issue by jmp-werewolf** [kimyearho/SharePod#1]
안녕하세요~
youtube 동영상을 자주 보는 사람입니다.
좋은거 배포해주셔서 잘사용하고 있습니다.

기능추가 요청건인데요....
1. 동영상 다운로드 여부
2. 키워드 검색 후 mp3 다운로드 가능한 정보를 리스트내에서도 보일 수 있는지 여부
3. SharePod 전체창 배경변경 가능여부

애정이 생겨 좀 많이 쓴거 아닌가 싶기도하네요....^^;
개발자님 화이팅입니다~

**Comment by kimyearho** [comment]
안녕하세요

동영상 다운로드는 이미 고려사항입니다
다만, 재생타임이나 용량에 따른 서버 처리율을 면밀히 검토 해봐야 할듯 합니다.
테스트에 큰 문제가 없다고 판단되면, 다음 버전에서 업데이트 하겠습니다.

키워드 검색 후 MP3 다운로드 가능한지 목록에서 확인할 수 있도록 하지 않은것은,
그렇게 디자인 되었습니다. 현재는 음악을 선택하면 다운로드 가능한지 아닌지 여부를
플레이어 창에서 확인할 수 있습니다. 이것은 음악을 듣지 않고 다운로드만 받고자 하는것은,
플레이어 취지에 맞지 않는다고 판단하여 디자인 하였습니다. 해당 내용은 당분간은 수정되지
않을 것 입니다.

3번 내용은 검토 해보겠습니다

**Comment by jmp-werewolf** [comment]
안녕하세요~

버그발견 공유 드립니다.
플레이어창을 빠르게 클릭시 플레이어리스트에서 무한조회현상이 발견되었습니다.

수고하세요~

**Comment by kimyearho** [comment]
안녕하세요
버그 공유 감사합니다.
해당 내용은 면밀히 검토 후 다음 버전에서 픽스 하겠습니다.
